version: "3.8"
services:
  web:
    build: .
    container_name: accessible-games
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app
      FLASK_ENV: production
    command: flask run --host=0.0.0.0
